[build]
  publish = "dist/feined-client/browser"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://feined-server.s11a.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://todo.s11a.com"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Expose-Headers = "Set-Cookie"